name: Firmware CI Check
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
        fail-fast: false
        matrix:
            flavor: [ARM9X, X9LITE, X7, XLITE, X9, COLORLCD]

    steps:
        - uses: actions/checkout@v2
        - uses: fiam/arm-none-eabi-gcc@v1
          with:
            release: 4.7-2013-q3
        - run: sudo apt-get update
        - run: sudo apt-get install -y cmake curl python3-pip libfox-1.6-dev qtbase5-dev qtmultimedia5-dev libqt5svg5-dev qttools5-dev qttools5-dev-tools 
        - run: sudo ln -sf /usr/bin/python3 /usr/bin/python
        - run: python3 -m pip install pillow clang
        - run: ./tools/commit-tests.sh
          env:
            FLAVOR: ${{ matrix.flavor }}
